# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://Fersox.github.io
date_format: "ordinal"
title: Fersox
subtitle: "厚积薄发"
description: "个人博客"
keywords:
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: jianyu.wang
organization: Mtime, Inc.
organization_url: http://www.mtime.com/
location: Beijing, China
email: jianyu.wang2013@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
redcarpet:
    extensions: ["tables"]
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: Fersox/Fersox.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: Fersox
douban_username: Fersox
facebook_username: Fersox
weibo_username: Fersox
zhihu_username: Fersox
twitter_username: Fersox

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
#duoshuo_username: mazhuang
#disqus_username: mzlogin
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, Design Patterns,Jquery,TypeScipt]

